#!/bin/bash

# example of script to add token to local dns using nsupdate

dnskeyfile=/dev/null
if [ -f "$3" ]
then
	dnskeyfile="$3"
fi

fulldomain="$1"
token="$2"

updatefile=$(mktemp)

printf "update delete _acme-challenge.%s. 300 in TXT \"%s\"\n\n" "${fulldomain}" "${token}" > "${updatefile}"

nsupdate -d -k "${dnskeyfile}" -v "${updatefile}"

rm -f "${updatefile}"
